### PR TITLE
has_shape() return true for NUL type only if element actually exists (fix #132)

### LINKED ISSUE #132: has_shape() always returns true when used with json11::Json::NUL
Calling `item.has_shape({ {"foo", json11::Json::NUL } }, err)` will always return true, whether "foo" exists or not. There does not appear to be a way to determine if a key exists in an object with an actual "null" value, for example for `{ "foo": null }`

Calling `item.has_shape({ {"foo", json11::Json::NUL } }, err)` on a JSON object of `{ "bar": 123 }` will also return true, even though there is no "foo" key in the object.

It appears at though has_shape() calls the JsonObject [] operator which, of course, returns static_null() if the value is not found, which is what results in has_shape() returning true. Perhaps there's another way to determine if a key exists with a null value, or better yet a way to determine if a key exists regardless of the data type?

### PR DESCRIPTION
**Pull request by jbhelm**
Fixes issue #132

### CODE REVIEW

**Comment by jbhelm** [comment]
Note the alternative to checking for static_null() as implemented in the PR is to just stop using operator[] and do something more like:
```
const auto& obj_items = object_items();
for (auto & item : types) {
    const auto it = obj_items.find(item.first);
    if (it == obj_items.cend() || it->second.type() != item.second) {
...
```

**Comment by jbhelm** [comment]
I agree with your points about the use of static_null() (which is why I posted the alternative above) -- I was attempting to continue use of operator[] in has_shape() to keep with its existing implementation. I've updated the PR to the version posted above.

I understand the default-value behavior of the library when accessing fields, however IMHO has_shape() as having a different purpose. The object `{ "bar": 123 }` definitely does _not_ "have the shape of" `{"foo", json11::Json::NUL }`. However I understand if you don't want to incorporated this PR, but I'll leave it in my fork in case anyone else needs to distinguish between default-null valued and non-existent fields.

**Comment by artwyman** [comment]
Approved.  This is a behavior change, but I feel it's unlikely that anyone actually wanted or depended on the old behavior.

@jbhelm I can't merge this until you sign the CLA here: https://opensource.dropbox.com/cla/

**Comment by artwyman** [comment]
Looks like CLA was signed on Apr 11, but I didn't notice because of a typo in the GitHub username.  Will merge.

**Pull request merged**
