### PR TITLE
Add compatibility with older 2.8 version of CMake

### PR DESCRIPTION
**Pull request by jcsilva**
Some legacy systems (Ubuntu 14.04, RHEL7.2) have older versions of CMake.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@jcsilva, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by artwyman** [comment]
I don't use CMake myself (it's a community-supported addition to this library) but I notice that your latest commit indicates removing version "temporarily".  Do you plan further changes before proposing that this be merged?

**Comment by akira-miasato** [comment]
Sorry for the hassle. The "temporary" commit was indeed a WIP, and the new commit should add compatibility with legacy CMake2.8 and avoid a CMake >=3.3 error of deprecated [CMP0038](https://cmake.org/cmake/help/v3.3/policy/CMP0048.html) policy. As it stands, it looks good to go.

**Comment by artwyman** [comment]
You'll need to sign the CLA online before I can merge.
I'm also curious if any CMake users such as @4brunu have any issue with this.

**Comment by 4brunu** [comment]
I tested and it works here...

**Comment by akira-miasato** [comment]
I have signed the CLA, but if it is the requester who needs to sign it, I can make a new pull request.

**Comment by artwyman** [comment]
@akira-miasato your name is on all the commits in the current version, which seems like it should be sufficient for legal purposes.  The smarxbot won't check automatically for a non-submitter, but I just confirmed that your CLA response is logged.

**Pull request merged**
