### PR TITLE
Add long support

### PR DESCRIPTION
**Pull request by saarnp**
Add long support

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@saarnp, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/) and update the thread so we can consider merging your code.

**Comment by saarnp** [comment]
Signed in.. Thanks :)

**Comment by j4cbo** [comment]
This is something we chose not to support as a design decision. The danger with embedding anything bigger than `int` in JSON is that it'll result in JSON that doesn't cleanly round-trip through some languages (notably Javascript itself). Storing long / int64_t / etc "natively" in JSON is tempting, but it can backfire and be very painful to deal with later on because of the compatibility issues that come up.

**Comment by artwyman** [comment]
What J4cbo said regarding compatibility.  It might be worth capturing this design decision in a comment somewhere, preferably attached to some static asserts of the assumptions involved.  Specifically, the current design assumes that an int fits into the mantissa bits of a double, which I don't think the language spec guarantees.

Since there are valid use cases where JavaScript compatibility doesn't matter, I wouldn't be averse to adding 64-bit integer support via optional #ifdefs or run-time flags.  However, I think it would be best to do it using int64_t rather than long, and to provide some error checking behavior around potentially dangerous casts by making them explicit, or having them throw or assert.

**Comment by j4cbo** [comment]
There are some comments here: https://github.com/dropbox/json11/blob/master/json11.hpp#L16-L27

**Comment by artwyman** [comment]
Per the discussion above, this feature is intentionally not included.

**Pull request closed without merging**
